### ISSUE TITLE
php版

### ISSUE THREAD

**Issue by xingline** [SukkaW/zsh-ipip#1]
请问能弄个php版本的ipip判断ip是否为IDCd的IP，我付费，谢谢

**Comment by SukkaW** [comment]
IPIP 数据库价格： https://www.ipip.net/product/ip.html
IPIP 销售邮箱：`sales@ipip.net`
北京天特信科技有限公司联系电话：`010-85867767`

IPDB 解析库（PHP）： https://github.com/ipipdotnet/ipdb-php
DATX 解析库（PHP）： https://github.com/ipipdotnet/datx-php
